framework:
    messenger:
        default_bus: query.bus

        buses:
            query.bus:
                default_middleware: false
                middleware:
                    - handle_message

            command.bus:
                default_middleware: false
                middleware:
                    - handle_message

            messenger.bus.event.async:
                default_middleware: allow_no_handlers
